title: Serhiy Novosad # your name (or website title) here
logo: "/images/12.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with over 5 years of experience as BIM Manager/Structural designer, broad practice working with and analyze data produced during design process, and extensive Data Science Course.
  <br><br>
  Work in construction sector made me detail-oriented and pay close attention to the nuances of a project, to make sure everything is done to the best of my ability.
  <br><br>
  <a href="https://www.linkedin.com/in/snovosad/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
