title: Serhiy Novosad # your name (or website title) here
logo: "/images/1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BIM Manager/Structural designer with over 5 years of experience, I have extensive practice working with and managing 3D models
  and data produced during modeling, which has further fueled my passion for data itself. 
  Currently taking part in a Data Science Course to develop my skills in the field. 
  <br><br>
  I am a hands-on professional who is constantly seeking to develop new skills and implement innovative solutions and technologies
  to improve performance and achieve better results. Work in construction sector made me detail-oriented and pay close attention 
  to the nuances of a project, to make sure everything is done to the best of my ability.
  <br><br>
  <a href="https://www.linkedin.com/in/snovosad/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
